import { ContentPage } from "../../ui/styles/Content";

export function ArquivoRemessa() {
  return(
    <ContentPage>
    <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>
      <b>Arquico</b><br/>

    </ContentPage>
  )
}