export const Menu = [
  {
    page:'Overview',
    link:'/',
  },
  {
    page:'Início',
    link:'/home',
  },
  {
    page:'Documentação de API',
    link:'/APIdocument',
  },
  // Certifique-se de configurar uma página e uma rota de cada página
];


export const ContentCards = [
  {
    title: 'Primeiro Card',
    subtitle: null,
    divisor: '',
    paragraph:`Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium deserunt, dolorem quia sequi fuga modi.`,
    phrase: null ,
    button: null,
    link:'/',
  },
  {
    title: 'Segundo Card',
    subtitle: null,
    divisor: false,
    paragraph:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium libero voluptatem eaque dolore aperiam.",
    phrase: null,
    button:'Ver repositório',
    link:'/link',
  },
  // Não ultrapasse o limite de 2 cards
]


export const Pages = [
  // {
  //   page: 'Wellcome',
  //   content:[
  //     {
  //       isCard: null,
  //       icon: null,
  //       head:"Bem vindo ao Projeto",
  //       title: null,
  //       subtitle: null,
  //       divisor: false,
  //       paragraph:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium deserunt, dolorem quia sequi fuga modi libero voluptatem eaque dolore aperiam, nemo ab architecto labore ut non autem facilis! Voluptatibus, rem. \n\nLorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium deserunt, dolorem quia sequi fuga modi libero voluptatem eaque dolore aperiam, nemo ab architecto labore ut non autem facilis! Voluptatibus, rem.",
  //       phrase:"Funil de vendas simples",
  //       code: null,
  //     },
  //     {
  //       isCard: null,
  //       icon: null,
  //       head:"OverView",
  //       title:"Coloque seu título aqui",
  //       divisor: false,
  //       subtitle:"Veja como fica o paragrafo abaixo",
  //       paragraph:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium deserunt, dolorem quia sequi fuga modi libero voluptatem eaque dolore aperiam, nemo ab architecto labore ut non autem facilis! Voluptatibus, rem.",
  //       phrase:"Funil de vendas simples",
  //       code: null,
  //     },
  //   ]
  // },
  // {
  //   page: 'OverView',
  //   content:[
  //     {
  //       isCard: null,
  //       icon: null,
  //       head:"OverView",
  //       title:"Coloque seu título aqui",
  //       divisor: false,
  //       subtitle:"Veja como fica o paragrafo abaixo",
  //       paragraph:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium deserunt, dolorem quia sequi fuga modi libero voluptatem eaque dolore aperiam, nemo ab architecto labore ut non autem facilis! Voluptatibus, rem.",
  //       phrase:"Funil de vendas simples",
  //       code: null,
  //     },
  //   ]
  // },
  // {
  //   page: 'Documentação',
  //   content:[
  //     {
  //       isCard: null,
  //       icon: null,
  //       head:"Documentação de API",
  //       title: null,
  //       subtitle: 'Estruture a aplicação para a documentação de sua API',
  //       divisor: true,
  //       paragraph:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium deserunt, dolorem quia sequi fuga modi libero voluptatem eaque dolore aperiam, nemo ab architecto labore ut non autem facilis! Voluptatibus, rem.",
  //       phrase:"Funil de vendas simples",
  //       code: null,
  //     },
  //   ]
  // }
];


export const HomePage = [
  {
    isCard: null,
    icon: null,
    head:"Bem vindo ao Projeto",
    title: null,
    subtitle: null,
    divisor: false,
    paragraph:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium deserunt, dolorem quia sequi fuga modi libero voluptatem eaque dolore aperiam, nemo ab architecto labore ut non autem facilis! Voluptatibus, rem. \n\nLorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium deserunt, dolorem quia sequi fuga modi libero voluptatem eaque dolore aperiam, nemo ab architecto labore ut non autem facilis! Voluptatibus, rem.",
    phrase:"Funil de vendas simples",
    code: null,
  },
  {
    isCard: null,
    icon: null,
    head: null,
    title: "Esse é um container só com o head ",
    subtitle: null,
    divisor: false,
    paragraph:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium deserunt, dolorem quia sequi fuga modi libero voluptatem eaque dolore aperiam, nemo ab architecto labore ut non autem facilis! Voluptatibus, rem.",
    phrase:"Funil de vendas simples",
    code: null,
  },
  {
    isCard: null,
    icon: null,
    head:"Bem vindo ao",
    title:"Faça a gestão de suas vendas:",
    subtitle:"Usuário único",
    divisor: false,
    paragraph:"Funil de vendas simples",
    phrase:"Funil de vendas simples",
    code:"docker-compose up-d",
  },
  {
    isCard: null,
    icon: null,
    head:"Bem vindo ao Projeto",
    title:"Coloque seu título aqui",
    divisor: false,
    subtitle:"Veja como fica o paragrafo abaixo",
    paragraph:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium deserunt, dolorem quia sequi fuga modi libero voluptatem eaque dolore aperiam, nemo ab architecto labore ut non autem facilis! Voluptatibus, rem.",
    phrase:"Funil de vendas simples",
    code: null,
  },
  {
    isCard: null,
    icon: null,
    head:"Esse é um container só com o head ",
    title: null,
    subtitle: null,
    divisor: false,
    paragraph:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium deserunt, dolorem quia sequi fuga modi libero voluptatem eaque dolore aperiam, nemo ab architecto labore ut non autem facilis! Voluptatibus, rem.",
    phrase:"Funil de vendas simples",
    code: null,
  },
  {
    isCard: null,
    icon: null,
    head:"Bem vindo ao",
    title:"Faça a gestão de suas vendas:",
    subtitle:"Usuário único",
    divisor: false,
    paragraph:"Funil de vendas simples",
    phrase:"Funil de vendas simples",
    code:"docker-compose up-d",
  },
];

export const Overview = [
  {
    isCard: null,
    icon: null,
    head:"OverView",
    title:"Coloque seu título aqui",
    divisor: false,
    subtitle:"Veja como fica o paragrafo abaixo",
    paragraph:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium deserunt, dolorem quia sequi fuga modi libero voluptatem eaque dolore aperiam, nemo ab architecto labore ut non autem facilis! Voluptatibus, rem.",
    phrase:"Funil de vendas simples",
    code: null,
  },
  {
    isCard: null,
    icon: null,
    head:"Esse é um container só com o head ",
    title: null,
    subtitle: null,
    divisor: false,
    paragraph:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium deserunt, dolorem quia sequi fuga modi libero voluptatem eaque dolore aperiam, nemo ab architecto labore ut non autem facilis! Voluptatibus, rem.",
    phrase:"Funil de vendas simples",
    code: null,
  },
  {
    isCard: null,
    icon: null,
    head:"Bem vindo ao",
    title:"Faça a gestão de suas vendas:",
    subtitle:"Usuário único",
    divisor: false,
    paragraph:"Funil de vendas simples",
    phrase:"Funil de vendas simples",
    code:"docker-compose up-d",
  },
  {
    isCard: null,
    icon: null,
    head:"Bem vindo ao Projeto",
    title:"Coloque seu título aqui",
    divisor: false,
    subtitle:"Veja como fica o paragrafo abaixo",
    paragraph:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium deserunt, dolorem quia sequi fuga modi libero voluptatem eaque dolore aperiam, nemo ab architecto labore ut non autem facilis! Voluptatibus, rem.",
    phrase:"Funil de vendas simples",
    code: null,
  },
  {
    isCard: null,
    icon: null,
    head:"Esse é um container só com o head ",
    title: null,
    subtitle: null,
    divisor: false,
    paragraph:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium deserunt, dolorem quia sequi fuga modi libero voluptatem eaque dolore aperiam, nemo ab architecto labore ut non autem facilis! Voluptatibus, rem.",
    phrase:"Funil de vendas simples",
    code: null,
  },
  {
    isCard: null,
    icon: null,
    head:"Bem vindo ao",
    title:"Faça a gestão de suas vendas:",
    subtitle:"Usuário único",
    divisor: false,
    paragraph:"Funil de vendas simples",
    phrase:"Funil de vendas simples",
    code:"docker-compose up-d",
  },
];
export const Documentation = [
  {
    isCard: null,
    icon: null,
    head:"Documentação de API",
    title: null,
    subtitle: 'Estruture a aplicação para a documentação de sua API',
    divisor: true,
    paragraph:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium deserunt, dolorem quia sequi fuga modi libero voluptatem eaque dolore aperiam, nemo ab architecto labore ut non autem facilis! Voluptatibus, rem.",
    phrase:"Funil de vendas simples",
    code: null,
  },
  {
    isCard: true,
    icon: 'fa fa-circle-info',
    head: null,
    title: 'Trabalhando com cards',
    subtitle: null,
    divisor: null,
    paragraph: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium deserunt, dolorem quia sequi fuga modi libero voluptatem eaque dolore aperiam, nemo ab architecto labore ut non autem facilis! Voluptatibus, rem.',
    phrase: null,
    code: 'const typeorm migration:run',
  },
  {
    isCard: null,
    icon: null,
    head: 'Inserindo códigos',
    title: null,
    subtitle: "Veja como você pode inserir um modelo Json no codespace no exemplo abaixo",
    divisor: null,
    paragraph:"Acessando o arquivo labels.jsx, você pode visualizar um modelo de um arquivo .json escrito para essa documentação, ao você inserir as chaves `{ } com o conteudo dentro, o Guide irá reconhecer que o código que você inseriu é do tipo Json`",
    phrase: 'Inserindo o código, o codespace irá retornar o resultado abaixo:',
    code:`const`,
  },
  {
    isCard: null,
    icon: null,
    head: null,
    title: 'Inserindo comandos de terminal',
    subtitle: "Veja como você pode inserir um modelo Json no codespace no exemplo abaixo",
    divisor: null,
    paragraph:"Acessando o arquivo labels.jsx, você pode visualizar um modelo de um arquivo .json escrito para essa documentação, ao você inserir as chaves `{ } com o conteudo dentro, o Guide irá reconhecer que o código que você inseriu é do tipo Json`",
    phrase: 'Inserindo o código, o codespace irá retornar o resultado abaixo:',
    code:`{ \n \ node:{\n \ \ yarn,\n \ \ vim,\n \ } \n}`,
  },
  {
    isCard: null,
    icon: null,
    head: null,
    title: 'Inserindo formatos .json',
    subtitle: "Veja como você pode inserir um modelo Json no codespace no exemplo abaixo",
    divisor: null,
    paragraph:"Acessando o arquivo labels.jsx, você pode visualizar um modelo de um arquivo .json escrito para essa documentação, ao você inserir as chaves `{ } com o conteudo dentro, o Guide irá reconhecer que o código que você inseriu é do tipo Json`",
    phrase: 'Inserindo o código, o codespace irá retornar o resultado abaixo:',
    code:`{ \n \ node:{\n \ \ yarn,\n \ \ vim,\n \ } \n}`,
  },
];
