export const Menu = [
  {
    page:'Overview',
    link:'/',
  },
];


export const HomePage = [
  {
    head:"Bem vindo ao Projeto",
    title:"Coloque seu título aqui",
    divisor: false,
    subtitle:"Veja como fica o paragrafo abaixo",
    paragraph:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium deserunt, dolorem quia sequi fuga modi libero voluptatem eaque dolore aperiam, nemo ab architecto labore ut non autem facilis! Voluptatibus, rem.",
    phrase:"Funil de vendas simples",
    code: null,
  },
  {
    head:"Esse é um container só com o head ",
    title: null,
    subtitle: null,
    divisor: false,
    paragraph:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium deserunt, dolorem quia sequi fuga modi libero voluptatem eaque dolore aperiam, nemo ab architecto labore ut non autem facilis! Voluptatibus, rem.",
    phrase:"Funil de vendas simples",
    code: null,
  },
  {
    head:"Bem vindo ao",
    title:"Faça a gestão de suas vendas:",
    subtitle:"Usuário único",
    divisor: false,
    paragraph:"Funil de vendas simples",
    phrase:"Funil de vendas simples",
    code:"docker-compose up-d",
  },
  {
    head:"Bem vindo ao Projeto",
    title:"Coloque seu título aqui",
    divisor: false,
    subtitle:"Veja como fica o paragrafo abaixo",
    paragraph:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium deserunt, dolorem quia sequi fuga modi libero voluptatem eaque dolore aperiam, nemo ab architecto labore ut non autem facilis! Voluptatibus, rem.",
    phrase:"Funil de vendas simples",
    code: null,
  },
  {
    head:"Esse é um container só com o head ",
    title: null,
    subtitle: null,
    divisor: false,
    paragraph:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium deserunt, dolorem quia sequi fuga modi libero voluptatem eaque dolore aperiam, nemo ab architecto labore ut non autem facilis! Voluptatibus, rem.",
    phrase:"Funil de vendas simples",
    code: null,
  },
  {
    head:"Bem vindo ao",
    title:"Faça a gestão de suas vendas:",
    subtitle:"Usuário único",
    divisor: false,
    paragraph:"Funil de vendas simples",
    phrase:"Funil de vendas simples",
    code:"docker-compose up-d",
  },
];

export const Overview = [
  {
    head:"OverView",
    title:"Coloque seu título aqui",
    divisor: false,
    subtitle:"Veja como fica o paragrafo abaixo",
    paragraph:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium deserunt, dolorem quia sequi fuga modi libero voluptatem eaque dolore aperiam, nemo ab architecto labore ut non autem facilis! Voluptatibus, rem.",
    phrase:"Funil de vendas simples",
    code: null,
  },
  {
    head:"Esse é um container só com o head ",
    title: null,
    subtitle: null,
    divisor: false,
    paragraph:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium deserunt, dolorem quia sequi fuga modi libero voluptatem eaque dolore aperiam, nemo ab architecto labore ut non autem facilis! Voluptatibus, rem.",
    phrase:"Funil de vendas simples",
    code: null,
  },
  {
    head:"Bem vindo ao",
    title:"Faça a gestão de suas vendas:",
    subtitle:"Usuário único",
    divisor: false,
    paragraph:"Funil de vendas simples",
    phrase:"Funil de vendas simples",
    code:"docker-compose up-d",
  },
  {
    head:"Bem vindo ao Projeto",
    title:"Coloque seu título aqui",
    divisor: false,
    subtitle:"Veja como fica o paragrafo abaixo",
    paragraph:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium deserunt, dolorem quia sequi fuga modi libero voluptatem eaque dolore aperiam, nemo ab architecto labore ut non autem facilis! Voluptatibus, rem.",
    phrase:"Funil de vendas simples",
    code: null,
  },
  {
    head:"Esse é um container só com o head ",
    title: null,
    subtitle: null,
    divisor: false,
    paragraph:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium deserunt, dolorem quia sequi fuga modi libero voluptatem eaque dolore aperiam, nemo ab architecto labore ut non autem facilis! Voluptatibus, rem.",
    phrase:"Funil de vendas simples",
    code: null,
  },
  {
    head:"Bem vindo ao",
    title:"Faça a gestão de suas vendas:",
    subtitle:"Usuário único",
    divisor: false,
    paragraph:"Funil de vendas simples",
    phrase:"Funil de vendas simples",
    code:"docker-compose up-d",
  },
];

export const ContentCards = [
  {
    title: 'Primeiro Card',
    subtitle: null,
    divisor: false,
    paragraph:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium deserunt, dolorem quia sequi fuga modi libero voluptatem eaque dolore aperiam, nemo ab architecto labore ut non autem facilis! Voluptatibus, rem.",
    phrase:"Funil de vendas simples",
    button:'Ver repositório',
    link:'/',
  },
  {
    title: 'Segundo Card',
    subtitle: null,
    divisor: false,
    paragraph:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium deserunt, dolorem quia sequi fuga modi libero voluptatem eaque dolore aperiam, nemo ab architecto labore ut non autem facilis! Voluptatibus, rem.",
    phrase:"Funil de vendas simples",
    button:'Ver repositório',
    link:'/',
  },
  {
    title: 'Segundo Card',
    subtitle: null,
    divisor: false,
    paragraph:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium deserunt, dolorem quia sequi fuga modi libero voluptatem eaque dolore aperiam, nemo ab architecto labore ut non autem facilis! Voluptatibus, rem.",
    phrase:"Funil de vendas simples",
    button:'Ver repositório',
    link:'/',
  },
]